# Test Configuration for Organoid pySCENIC Pipeline
# This configuration uses existing pySCENIC results for testing

# Experiment settings
experiment:
  name: "organoid_morphogen_test"
  description: "Test run using existing pySCENIC results"
  cell_lines: ["H1", "H9", "WIBJ2", "WTC", "combined"]
  
# Input data settings
data:
  input_dir: "../data"
  # Use existing count matrices
  count_files:
    H1: "exp1_counts_for_scenic_H1.h5ad"
    H9: "exp1_counts_for_scenic_H9.h5ad"
    WIBJ2: "exp1_counts_for_scenic_WIBJ2.h5ad"
    WTC: "exp1_counts_for_scenic_WTC.h5ad"
    combined: "exp1_counts_for_scenic.h5ad"
  
# pySCENIC workflow settings
pyscenic:
  # Set to false to skip running pySCENIC and use existing results
  run_pyscenic: false
  
  # Paths to existing pySCENIC results
  existing_results:
    base_dir: "../pyscenic_celline/results/cell_line"
    adjacencies_pattern: "adjacencies_seed_{seed}.csv"
    enriched_motifs_pattern: "enriched_motifs_seed_{seed}.p"
    regulons_pattern: "regulons_seed_{seed}.p"
    modules_pattern: "modules_seed_{seed}.p"
    
  # Seeds to use for consensus (subset of available seeds)
  seeds: [25, 27, 30, 32, 44, 46, 71, 80, 81, 89, 94, 95, 99]
  
  # Consensus settings
  consensus:
    min_seed_fraction: 0.3  # Regulon must appear in 30% of seeds
    min_targets: 5  # Minimum targets per regulon
    
  # AUCell settings  
  aucell:
    num_workers: 4
    auc_threshold: 0.05
    
# Analysis settings
analysis:
  morphogens:
    # Morphogen genes of interest
    genes: 
      - "WNT3A"
      - "BMP4" 
      - "ACTIVIN"
      - "FGF2"
      - "NODAL"
    
  # Correlation analysis
  correlation:
    method: "spearman"
    min_correlation: 0.3
    
  # Visualization
  plotting:
    dpi: 300
    figure_format: "png"
    color_palette: "viridis"
    
# Output settings
output:
  results_dir: "test_results"
  save_intermediates: true
  create_loom: false  # Skip loom creation for testing
  
# Computational settings
compute:
  n_cores: 4
  memory_limit: "8GB"
  chunk_size: 1000
  
# Logging
logging:
  level: "INFO"
  log_file: "test_pyscenic.log"
